
export const metadata = {
  title: 'contact',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>Swagat h aapka {children}</body>
    </html>
  )
}